### ISSUE TITLE
Prompts

### ISSUE THREAD

**Issue by Paulpey13** [marrlab/HistoGPT#16]
Hello, first, this project and models are very nice !

I am encountering an issue where the model seems to ignore my prompts. No matter what I input, the output is almost always the same and does not reflect the given prompt. Do you have any idea why this might be happening?

Thank you.

**Comment by manuel-tran** [comment]
Hi Paulpey13,

I would recommend treating HistoGPT as a text completion model rather than a chat completion model. We have trained HistoGPT to simply write a report. This means that if you give the model a fragment of the report, it will try to complete it (like any language model that is not fine-tuned for conversation). For example, if you type the sentence "The tumor thickness is", the model will complete the sentence as "The tumor thickness is 1.2 mm" and continue with the rest of the report. A chat completion model (like ChatGPT), on the other hand, would give you more natural answers, as you would expect from a human conversation. We are actively working on such an extension. Stay tuned!

Best wishes.

**Comment by Paulpey13** [comment]
Okay I understand,

Thank you for your answer and your amazing work !

Best wishes
